---
"on":
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
   
    
name: Runner
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_REPOSITORY: github-runners
      GITHUB_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    defaults:
        run:
         working-directory: "."     
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          install: true

      - name: Build Image
        if: ${{ github.event_name == 'pull_request' }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
          load: false
          
      - name: Login to DockerHub
        if: ${{ github.event_name == 'push' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push
        if: ${{ github.event_name == 'push' }}
        id: docker_build_and_push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          load: false
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest
          #cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:buildcache
          #cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:buildcache,mode=max
      
      -  name: Test
         run: |
          docker run --detach --name my-runner -e RUNNER_NAME=my-runner -e GITHUB_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} -e RUNNER_REPOSITORY_URL=https://github.com/obynodavid12/docker-actions -v /var/run/docker.sock:/var/run/docker.sock ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest
          #docker run --rm ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPOSITORY }}:latest --name my-runner -e RUNNER_NAME=my-runner -e GITHUB_ACCESS_TOKEN=${{ secrets.PERSONAL_ACCESS_TOKEN }} -e RUNNER_REPOSITORY_URL=https://github.com/obynodavid12/docker-actions -v /var/run/docker.sock:/var/run/docker.sock 
     
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} ${{ steps.docker_build_and_push.outputs.digest}}
